GET http://localhost:3000/users

###

GET http://localhost:3000/users/659709eae5cceb7c6549e63

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Mo"
}

###

DELETE http://localhost:3000/users/6549709eae5cceb7c6549e63